title: Tovertypen.nl
description: "De snelste manier om te typen: je computer het laten doen."
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Digitale Fitheid: https://www.digitalefitheid.nl
